### ISSUE TITLE
JW7-3.2: Fatal error after ugrade to Moodle 3.3

### ISSUE THREAD

**Issue by multiplexer2** [lucisgit/moodle-filter_jwplayer#70] opened 2017-06-20 11:03 UTC
After an upgrade of Moodle from 3.2 (with filter_jwplayer for 3.2 installed) to 3.3, Moodle crashes with a fatal error:

Fatal error: Class filter_jwplayer_manager may not inherit from final class (core_media_manager) in /filter/jwplayer/classes/manager.php on line 36

**Comment by kabalin** [comment] 2017-06-20 11:08
Yep, known issue caused by https://tracker.moodle.org/browse/MDL-58361.

Try https://github.com/lucisgit/moodle-media_jwplayer, it will be released soon as beta,. No readme yet, sorry, you need to remove filter plugin completely first, settings in new one are the same, location for deploying plugin is ./media/player/jwplayer. RTMP support does not work yet, but will be [soon](https://tracker.moodle.org/browse/MDL-59255).

**Closed as completed** 2017-07-11 11:06 UTC
Labels: wontfix
