### ISSUE TITLE
JW7 upgrade

### ISSUE THREAD

**Issue by kabalin** [lucisgit/moodle-filter_jwplayer#37] opened 2015-08-04 14:45 UTC
We need to make sure that plugin works with JW7. Particular attention needs to be paid to existing functionality that has changed in the new version:

* Skins (no longer support XML, @owenbarritt  already addressed it #34)
* Google analytics (trackingobject parameter is no longer needed according to [docs](http://support.jwplayer.com/customer/portal/articles/1417179-integration-with-google-analytics))
* License key changes
* Some paid functionality has become free (e.g. skins).

For the list of major changes, see [migration documentation](http://support.jwplayer.com/customer/portal/articles/2037989-migration-from-jw6-to-jw7).

In plugin maintenance we will proceed as follows:
* New JW6 branch will be created from master that will only contain JW6 related changes, only critical changes will be added to it in future.
* New JW7 branch will be created from 0.3 release tag and will be the current stable where all pull requests have to be created.
* Existing master will be deleted once all existing pull requests will be re-created to JW7 branch.

There will be no unstable branches at the moment, all unstable code should remain in developer's forks and added via pull request to corresponding stable branches when it is ready for revision and testing. As we do not have testers and unstable branch, there is a likely that pull request will stay open until I find time to merge them locally and test before merging to public branch. If anyone will be willing to test someone's else changes (not own pull request), that will help a lot.

**Comment by kabalin** [comment] 2015-08-04 14:48
@owenbarritt, @jojoob, @tonyjbutler just mentioned you guys at this comment to make sure you have seen upcoming changes above. Feel free to ask question and suggest any improvements to branching/release policy.

**Comment by owenbarritt** [comment] 2015-08-10 09:03
Having looked at the existing plugin with JW7 a couple of weeks ago:
- Skins are addressed in #34
- Google Analytics stuff is to do with how google's code is embedded within the site, the settings on the player itself are unchanged, so this probably doesn't require any changes to the code (have tested and appears to be working)
- JW7 works as expected if a JW7 licence key is given in the licence key option, so I'm not sure this needs any change to the plugin.

**Comment by owenbarritt** [comment] 2015-08-10 12:07
Just re-read the google analytics bit and see what you mean now.

The issue is then how to get the ga code in the player settings.  Either we need to set the idstring or label variables, which seem sensible at there defaults or pass ga as an empty object i.e. ga: {}.

When I was first putting this together without the trackingcode option, all my attempts ended up with an empty array ie. ga: [](which doesn't work) or a string ga: '{}' (which also doesn't work).  I'll try and have another look when I get a moment.

**Comment by owenbarritt** [comment] 2015-08-17 13:55
#43 should address the last 2 points:
- License key changes
- Some paid functionality has become free (e.g. skins).

**Comment by owenbarritt** [comment] 2015-08-17 16:02
#44 should address the google analytics stuff

**Closed** 2015-12-01 16:48 UTC
Labels: task

**Comment by kabalin** [comment] 2015-12-01 16:49
@owenbarritt Thanks for your hard work, the plugin is now released.
